spring:
   application:
      name: TODO
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    metadataMap:
      instanceId:  applicationname:${spring.application.instance_id:${random.value}}
    preferIpAddress: true
    statusPageUrlPath: /TODO

server:
  port: 0